default:
- override hydra/output: local
- override hydra/launcher: local
env: myoHandReachRandom-v0
algorithm: NPG
seed: 2
sample_mode: trajectories
rl_num_traj: 96
rl_num_samples: 0
num_cpu: 8
rl_num_iter: 1001
save_freq: 50
eval_rollouts: 10
exp_notes: 'J1a: Training performance for v0.1dev, hash 1a0ddda0040c332198375dcddaea4811f54736bb-mj_envs,
  931272aca91c674a17e7450352686b4d4cd1d1d8-neuromuscular_sim'
policy_size: (32, 32)
init_log_std: -0.25
min_log_std: -1.0
vf_hidden_size: (128, 128)
vf_batch_size: 64
vf_epochs: 2
vf_learn_rate: 0.001
rl_step_size: 0.1
rl_gamma: 0.995
rl_gae: 0.97
alg_hyper_params:
  device: cpu
job_name: npg_${env}
